import './style.css';
import { createClient } from '@supabase/supabase-js';
import { translations } from './translations.js';

const url = import.meta.env.VITE_SUPABASE_URL;
const key = import.meta.env.VITE_SUPABASE_ANON_KEY;
const configured = Boolean(url && key && !url.includes('YOUR-PROJECT'));
const supabase = configured ? createClient(url, key) : null;
const state = { lang: localStorage.getItem('haven-language') || 'en', session: null, profile: null, conversations: [], selected: null, messages: [], channel: null, authMode: 'login' };
const t = (key) => translations[state.lang]?.[key] || translations.en[key] || key;

const app = document.querySelector('#app');
app.innerHTML = `
  <aside class="emergency"><span data-i18n="emergency"></span><button class="link" data-action="crisis" data-i18n="crisisHelp"></button></aside>
  <header class="header"><a class="brand" href="#top"><span class="brand-mark">H</span> Haven</a><nav class="nav"><a href="#how" data-i18n="navHow"></a><a href="#safety" data-i18n="navSafety"></a><a href="#" data-action="moderator" data-i18n="moderatorArea"></a></nav><div class="header-actions"><select class="language-select" id="language"><option value="en">English</option><option value="de">Deutsch</option><option value="ar">العربية</option></select><span id="userPill"></span><button class="button small" data-action="auth" data-i18n="login"></button><button class="button small" data-action="logout" data-i18n="logout" hidden></button></div></header>
  <main id="top"><section class="hero"><div><p class="eyebrow" data-i18n="eyebrow"></p><h1 class="display" data-i18n="heroTitle"></h1><p class="hero-copy" data-i18n="heroText"></p><div class="actions"><button class="button primary" data-action="guest" data-i18n="startGuest"></button><button class="button" data-action="signup" data-i18n="createAccount"></button></div><ul class="trust-row"><li data-i18n="human"></li><li data-i18n="private"></li><li data-i18n="calm"></li></ul></div><div class="portrait-card"><span class="status" data-i18n="available"></span><blockquote class="quote" data-i18n="quote"></blockquote><div class="listener"><span class="avatar">M</span><strong data-i18n="listener"></strong></div></div></section>
  <section class="section" id="how"><p class="eyebrow" data-i18n="howLabel"></p><h2 class="section-title" data-i18n="howTitle"></h2><div class="cards"><article class="card"><span class="number">01</span><h3 data-i18n="step1"></h3><p data-i18n="step1Text"></p></article><article class="card"><span class="number">02</span><h3 data-i18n="step2"></h3><p data-i18n="step2Text"></p></article><article class="card"><span class="number">03</span><h3 data-i18n="step3"></h3><p data-i18n="step3Text"></p></article></div></section>
  <section class="safety" id="safety"><div><p class="eyebrow" data-i18n="safetyLabel"></p><h2 class="section-title" data-i18n="safetyTitle"></h2><p class="safety-copy" data-i18n="safetyText"></p></div><ul class="promises"><li><span class="check">✓</span><div><strong data-i18n="safety1"></strong><small data-i18n="safety1Text"></small></div></li><li><span class="check">✓</span><div><strong data-i18n="safety2"></strong><small data-i18n="safety2Text"></small></div></li><li><span class="check">✓</span><div><strong data-i18n="safety3"></strong><small data-i18n="safety3Text"></small></div></li></ul></section>
  <section class="closing"><p class="eyebrow" data-i18n="eyebrow"></p><h2 class="section-title" data-i18n="closing"></h2><p data-i18n="closingText"></p><button class="button primary" data-action="guest" data-i18n="startGuest"></button></section></main>
  <footer class="footer"><a class="brand" href="#top"><span class="brand-mark">H</span> Haven</a><p data-i18n="footer"></p><small data-i18n="footerNote"></small></footer>
  <div class="overlay" id="modal" hidden><section class="modal" id="modalCard" role="dialog" aria-modal="true"><button class="close" data-action="close">×</button><div id="modalBody"></div></section></div><div class="toast" id="toast" hidden></div>`;

function translate(){document.documentElement.lang=state.lang;document.documentElement.dir=state.lang==='ar'?'rtl':'ltr';document.querySelector('#language').value=state.lang;document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));renderHeader()}
function renderHeader(){const logged=Boolean(state.session);document.querySelector('[data-action="auth"]').hidden=logged;document.querySelector('[data-action="logout"]').hidden=!logged;const pill=document.querySelector('#userPill');pill.innerHTML=logged?`<span class="user-pill">${escapeHtml(state.profile?.display_name || (state.session.user.is_anonymous?'Guest':state.session.user.email))} · ${t(state.profile?.role==='moderator'?'roleModerator':'roleUser')}</span>`:''}
function showToast(message,error=false){const toast=document.querySelector('#toast');toast.textContent=message;toast.className=`toast${error?' error':''}`;toast.hidden=false;clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.hidden=true,4200)}
function showModal(html,wide=false){document.querySelector('#modalBody').innerHTML=html;document.querySelector('#modalCard').classList.toggle('wide',wide);document.querySelector('#modal').hidden=false;document.body.style.overflow='hidden'}
function closeModal(){document.querySelector('#modal').hidden=true;document.body.style.overflow='';unsubscribe()}
function escapeHtml(value=''){const div=document.createElement('div');div.textContent=value;return div.innerHTML}
function requireSetup(){if(configured)return false;showModal(`<div class="setup-box"><div class="setup-icon">⌁</div><p class="eyebrow">Supabase</p><h2>${t('setupTitle')}</h2><p class="modal-intro">${t('setupText')}</p></div>`);return true}

function guestModal(){if(requireSetup())return;showModal(`<p class="eyebrow">Haven</p><h2>${t('guestTitle')}</h2><p class="modal-intro">${t('guestText')}</p><form class="form" id="guestForm"><label class="field">${t('nickname')}<input name="nickname" maxlength="40" placeholder="${t('nicknamePlaceholder')}" required></label><button class="button primary" type="submit">${t('continue')}</button></form>`)}
function authModal(mode='login'){if(requireSetup())return;state.authMode=mode;const signup=mode==='signup';showModal(`<p class="eyebrow">Haven</p><h2>${t('authTitle')}</h2><p class="modal-intro">${t('authText')}</p><form class="form" id="authForm">${signup?`<label class="field">${t('displayName')}<input name="name" maxlength="50" required></label>`:''}<label class="field">${t('email')}<input name="email" type="email" required></label><label class="field">${t('password')}<input name="password" type="password" minlength="8" required></label><button class="button primary" type="submit">${t(signup?'signUp':'signIn')}</button><p class="form-note">${t(signup?'haveAccount':'noAccount')} <button type="button" class="link" data-action="switch-auth">${t(signup?'switchLogin':'switchSignup')}</button></p></form>`)}
function crisisModal(){showModal(`<p class="eyebrow">${t('crisisHelp')}</p><h2>${t('crisisTitle')}</h2><p class="modal-intro">${t('crisisText')}</p><p class="crisis-note">${t('crisisNote')}</p><button class="button primary" data-action="close">${t('understand')}</button>`)}

async function loadProfile(){if(!state.session)return;const {data}=await supabase.from('profiles').select('*').eq('id',state.session.user.id).single();state.profile=data;renderHeader()}
async function startGuest(nickname){const {data,error}=await supabase.auth.signInAnonymously({options:{data:{display_name:nickname}}});if(error)throw error;state.session=data.session;await loadProfile();conversationHome()}
async function submitAuth(form){const values=Object.fromEntries(new FormData(form));if(state.authMode==='signup'){const {data,error}=await supabase.auth.signUp({email:values.email,password:values.password,options:{data:{display_name:values.name}}});if(error)throw error;state.session=data.session;showToast(t('accountCreated'));if(data.session){await loadProfile();conversationHome()}else closeModal()}else{const {data,error}=await supabase.auth.signInWithPassword({email:values.email,password:values.password});if(error)throw error;state.session=data.session;await loadProfile();conversationHome()}}

async function conversationHome(){if(!state.session){authModal();return}const {data,error}=await supabase.from('conversations').select('*').order('created_at',{ascending:false});if(error)throw error;state.conversations=data||[];const active=state.conversations.find(c=>c.status!=='closed');if(active){await openConversation(active.id);return}showModal(`<p class="eyebrow">${t('chatLabel')}</p><h2>${t('newConversation')}</h2><form class="form" id="newChatForm"><label class="field">${t('topic')}<input name="topic" maxlength="100" placeholder="${t('topicPlaceholder')}" required></label><label class="field">${t('language')}<select name="language"><option value="en">English</option><option value="de">Deutsch</option><option value="ar">العربية</option></select></label><button class="button primary" type="submit">${t('findListener')}</button></form>`)}
async function createConversation(form){const values=Object.fromEntries(new FormData(form));const {data,error}=await supabase.from('conversations').insert({user_id:state.session.user.id,topic:values.topic,language:values.language}).select().single();if(error)throw error;await openConversation(data.id)}
async function openConversation(id){const {data:conversation,error}=await supabase.from('conversations').select('*').eq('id',id).single();if(error)throw error;state.selected=conversation;await loadMessages();renderConversation();subscribe(id)}
async function loadMessages(){const {data,error}=await supabase.from('messages').select('*').eq('conversation_id',state.selected.id).order('created_at');if(error)throw error;state.messages=data||[]}
function renderConversation(){const c=state.selected;const waiting=c.status==='waiting';showModal(`<p class="eyebrow">${t('chatLabel')}</p><div class="workspace"><aside class="sidebar"><h3>${t(waiting?'waiting':'active')}</h3><div class="notice">${waiting?t('waitingText'):escapeHtml(c.topic)}</div></aside><section class="conversation"><header class="conversation-head"><div><h3>${escapeHtml(c.topic)}</h3><small>${waiting?t('waiting'):t('active')}</small></div><button class="button small" data-action="end-chat">${t('endChat')}</button></header><div class="messages" id="messages">${messageHtml()}</div>${c.status==='closed'?`<div class="notice">${t('ended')}</div>`:`<form class="composer" id="messageForm"><textarea name="message" rows="2" maxlength="3000" placeholder="${t('messagePlaceholder')}" required></textarea><button class="button primary" type="submit">${t('send')}</button></form>`}</section></div>`,true);scrollMessages()}
function messageHtml(){if(!state.messages.length)return `<div class="empty-state">${t('waitingText')}</div>`;return state.messages.map(m=>`<div class="bubble${m.sender_id===state.session.user.id?' mine':''}">${escapeHtml(m.body)}<small>${new Date(m.created_at).toLocaleTimeString(state.lang,{hour:'2-digit',minute:'2-digit'})}</small></div>`).join('')}
function scrollMessages(){const box=document.querySelector('#messages');if(box)box.scrollTop=box.scrollHeight}
async function sendMessage(form){const text=new FormData(form).get('message').trim();if(!text)return;const {error}=await supabase.from('messages').insert({conversation_id:state.selected.id,sender_id:state.session.user.id,body:text});if(error)throw error;form.reset()}
function subscribe(id){unsubscribe();state.channel=supabase.channel(`conversation-${id}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages',filter:`conversation_id=eq.${id}`},payload=>{if(!state.messages.some(m=>m.id===payload.new.id)){state.messages.push(payload.new);const box=document.querySelector('#messages');if(box){box.innerHTML=messageHtml();scrollMessages()}}}).on('postgres_changes',{event:'UPDATE',schema:'public',table:'conversations',filter:`id=eq.${id}`},payload=>{state.selected=payload.new;renderConversation()}).subscribe()}
function unsubscribe(){if(state.channel&&supabase)supabase.removeChannel(state.channel);state.channel=null}

async function moderatorDashboard(){if(requireSetup())return;if(!state.session){authModal();return}await loadProfile();if(state.profile?.role!=='moderator'){showModal(`<div class="setup-box"><div class="setup-icon">◌</div><h2>${t('moderatorArea')}</h2><p>${t('moderatorOnly')}</p></div>`);return}const {data,error}=await supabase.from('conversations').select('*').in('status',['waiting','active']).order('created_at');if(error)throw error;state.conversations=data||[];const waiting=state.conversations.filter(c=>c.status==='waiting');const active=state.conversations.filter(c=>c.moderator_id===state.session.user.id&&c.status==='active');showModal(`<p class="eyebrow">Haven team</p><h2>${t('dashboard')}</h2><div class="workspace"><aside class="sidebar"><h3>${t('queue')}</h3><div class="chat-list">${waiting.length?waiting.map(chatItem).join(''):`<p>${t('emptyQueue')}</p>`}</div><h3>${t('active')}</h3><div class="chat-list">${active.map(chatItem).join('')}</div></aside><section class="conversation"><div class="empty-state">${t('chooseChat')}</div></section></div>`,true)}
function chatItem(c){return `<button class="chat-item" data-chat-id="${c.id}" data-status="${c.status}"><strong>${escapeHtml(c.topic)}</strong><small>${c.language.toUpperCase()} · ${new Date(c.created_at).toLocaleTimeString(state.lang,{hour:'2-digit',minute:'2-digit'})}</small></button>`}
async function moderatorOpen(id,status){if(status==='waiting'){const {error}=await supabase.rpc('accept_conversation',{conversation_uuid:id});if(error)throw error}await openConversation(id)}
async function endConversation(){const {error}=await supabase.rpc('close_conversation',{conversation_uuid:state.selected.id});if(error)throw error;state.selected.status='closed';renderConversation()}

document.addEventListener('click',async(event)=>{const action=event.target.closest('[data-action]')?.dataset.action;try{if(action==='guest'){state.session?await conversationHome():guestModal()}if(action==='auth')authModal();if(action==='signup'){state.session?await conversationHome():authModal('signup')}if(action==='switch-auth')authModal(state.authMode==='login'?'signup':'login');if(action==='crisis')crisisModal();if(action==='close')closeModal();if(action==='moderator')moderatorDashboard();if(action==='logout'){await supabase.auth.signOut();state.session=null;state.profile=null;closeModal();translate()}if(action==='end-chat')await endConversation();const item=event.target.closest('[data-chat-id]');if(item)await moderatorOpen(item.dataset.chatId,item.dataset.status)}catch(error){showToast(error.message||t('genericError'),true)}});
document.addEventListener('submit',async(event)=>{event.preventDefault();try{if(event.target.id==='guestForm')await startGuest(new FormData(event.target).get('nickname'));if(event.target.id==='authForm')await submitAuth(event.target);if(event.target.id==='newChatForm')await createConversation(event.target);if(event.target.id==='messageForm')await sendMessage(event.target)}catch(error){showToast(error.message||t('genericError'),true)}});
document.querySelector('#language').addEventListener('change',event=>{state.lang=event.target.value;localStorage.setItem('haven-language',state.lang);translate()});document.querySelector('#modal').addEventListener('click',event=>{if(event.target.id==='modal')closeModal()});document.addEventListener('keydown',event=>{if(event.key==='Escape')closeModal()});

async function init(){translate();if(!configured)return;const {data}=await supabase.auth.getSession();state.session=data.session;if(state.session)await loadProfile();supabase.auth.onAuthStateChange((_event,session)=>{state.session=session;if(!session){state.profile=null;renderHeader()}})}
init();
